### PR TITLE
german translation and remove of tecrd.com specific settings

### PR DESCRIPTION
**Pull request by rnwgnr**
I´ve came across your fork of mytinytodo and found the improvements very usefull.

I´ve added a german translation based on the original translation of mytinytodo.

The repo seems a bit of messed up with tecrd.com specific settings. I made adjustments to this:
- fixed requesting favicon from tecrd.com
- removed https-check for tecrd.com
- removed .htaccess and .htusers for basic auth on tecrd.com

The release package for 1.5 should be refreshed as

### CODE REVIEW

**Comment by MoonCactus** [comment]
Thanks! Github tells me it looks like your first pull request while this is my first merge from a pull request ;)

**Comment by MoonCactus** [comment]
By the way, would you be kind enough to delete and fork again my repo? As you probably noticed I accidentally posted my own mostly private todo list in the branch you forked and I would like to avoid distributing it publicly ;)
I cleaned it up by rewriting git history as described in https://help.github.com/articles/removing-sensitive-data-from-a-repository/ but it asks for a rebase from you in addition. I guess that a simpler way for you to avoid issues with the rewrite would probably be to delete and fork the repo again.
There are a few other enhancements aimed at making it easier to install and use, in the same order as what I merged from you. Sorry & thanks again!

**Comment by rnwgnr** [comment]
Hi,

i´ve delete my repo and will create a new fork if required.

I think it would be useful to rename the config.php as well, config.php-dist or the like would be apropiate. Otherwise an user edited config.php will be overwritten when pushing a new release to the users host.

**Comment by MoonCactus** [comment]
You are right -- actually I had added the whole db/* to .gitignore this morning for this very reason also but it broke the installation. I just fixed it (i.e. respects existing data, install fresh one when missing), and I have added a sample dummy db.

**Pull request merged**
